"""
Build Bayesian shooter/keeper profiles with credible intervals.

Writes:
- outputs/statsbomb/shooter_profiles.parquet
- outputs/statsbomb/keeper_profiles.parquet
- reports/profiles_sample.md  (well-sampled vs low-data confidence cards)

Run from the project root:
    python reports/build_profiles.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.models.bayesian import build_keeper_profiles, build_shooter_profiles

DATA_PATH = ROOT / "outputs" / "statsbomb" / "penalties_statsbomb_clean.parquet"
OUT_DIR = ROOT / "outputs" / "statsbomb"
SAMPLE_PATH = ROOT / "reports" / "profiles_sample.md"


def _pct(x: float) -> str:
    return f"{round(100 * x)}%"


def shooter_card(row: pd.Series) -> str:
    return (
        f"- **Shooter `{row['shooter_id']}`** - converts **{_pct(row['conv_rate_mean'])}** "
        f"({_pct(row['conv_ci_low'])}-{_pct(row['conv_ci_high'])}) over **{int(row['n_pens'])}** "
        f"pens, favors **{row['favored_zone']}** ({_pct(row['favored_zone_prob'])}). "
        f"Confidence: **{row['confidence']}**."
    )


def keeper_card(row: pd.Series) -> str:
    keeper_id = int(float(row["keeper_id"]))
    return (
        f"- **Keeper `{keeper_id}`** - saves **{_pct(row['save_rate_mean'])}** "
        f"({_pct(row['save_ci_low'])}-{_pct(row['save_ci_high'])}) over **{int(row['n_faced'])}** "
        f"faced. Confidence: **{row['confidence']}**."
    )


def main() -> None:
    penalties = pd.read_parquet(DATA_PATH)
    shooters = build_shooter_profiles(penalties)
    keepers = build_keeper_profiles(penalties)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    shooters.to_parquet(OUT_DIR / "shooter_profiles.parquet", index=False)
    keepers.to_parquet(OUT_DIR / "keeper_profiles.parquet", index=False)

    shooters_sorted = shooters.sort_values("n_pens", ascending=False)
    well = shooters_sorted.head(3)
    low = shooters_sorted[shooters_sorted["n_pens"] == 1].head(3)
    well_k = keepers.sort_values("n_faced", ascending=False).head(3)

    avg_width = (shooters["conv_ci_high"] - shooters["conv_ci_low"]).mean()
    sparse_width = (
        shooters.loc[shooters["n_pens"] <= 1, "conv_ci_high"]
        - shooters.loc[shooters["n_pens"] <= 1, "conv_ci_low"]
    ).mean()
    rich_width = (
        shooters.loc[shooters["n_pens"] >= 11, "conv_ci_high"]
        - shooters.loc[shooters["n_pens"] >= 11, "conv_ci_low"]
    ).mean()

    lines = [
        "# Bayesian profiles - sample confidence cards",
        "",
        "Generated by `python reports/build_profiles.py`. Conjugate Beta-Binomial / "
        "Dirichlet posteriors (no MCMC). 90% credible intervals; the interval widens "
        "as career sample shrinks.",
        "",
        f"- Shooters profiled: **{len(shooters)}**, keepers: **{len(keepers)}**.",
        f"- Mean 90% CI width (all shooters): **{avg_width:.3f}**.",
        f"- Mean CI width, <=1 pen (sparse): **{sparse_width:.3f}** "
        f"vs >=11 pens (rich): **{rich_width:.3f}** - uncertainty shrinks with data.",
        "",
        "## Well-sampled shooters",
        "",
        *[shooter_card(r) for _, r in well.iterrows()],
        "",
        "## Low-data shooters (1 pen - leans on prior)",
        "",
        *[shooter_card(r) for _, r in low.iterrows()],
        "",
        "## Well-sampled keepers",
        "",
        *[keeper_card(r) for _, r in well_k.iterrows()],
        "",
    ]
    SAMPLE_PATH.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {(OUT_DIR / 'shooter_profiles.parquet').relative_to(ROOT)}")
    print(f"Wrote {(OUT_DIR / 'keeper_profiles.parquet').relative_to(ROOT)}")
    print(f"Wrote {SAMPLE_PATH.relative_to(ROOT)}")
    print(f"sparse CI width {sparse_width:.3f} vs rich {rich_width:.3f}")


if __name__ == "__main__":
    main()
