"""
Generate the Step 6 baseline metrics report.

Run from the project root:
    python reports/build_baseline_table.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.evaluation.metrics import format_metric
from src.evaluation.splitters import temporal_cutoff_by_fraction, temporal_train_test_split
from src.features.build import build_modeling_table
from src.models.baselines import add_baseline_predictions, evaluate_baselines


DATA_PATH = ROOT / "outputs" / "statsbomb" / "penalties_statsbomb_clean.parquet"
REPORT_PATH = ROOT / "reports" / "baseline_table.md"


def _markdown_table(df: pd.DataFrame) -> str:
    columns = [
        "baseline",
        "log_loss",
        "brier",
        "brier_skill_score",
        "roc_auc",
        "pr_auc",
        "ece",
        "accuracy_footnote",
    ]
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join(["---"] * len(columns)) + " |"
    rows = []
    for _, row in df[columns].iterrows():
        values = [str(row["baseline"])]
        values.extend(format_metric(row[col]) for col in columns[1:])
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join([header, divider, *rows])


def build_report() -> str:
    penalties = pd.read_parquet(DATA_PATH)
    cutoff = temporal_cutoff_by_fraction(penalties, train_fraction=0.8)
    train, test = temporal_train_test_split(penalties, cutoff=cutoff)
    train_rate = float(train["outcome_bin"].mean())

    modeling_table = build_modeling_table(penalties)
    test_ids = set(test["penalty_id"])
    test_features = modeling_table[modeling_table["penalty_id"].isin(test_ids)].copy()
    with_predictions = add_baseline_predictions(test_features, global_rate=train_rate)
    metrics = evaluate_baselines(with_predictions)

    lines = [
        "# Baseline Metrics - Step 6",
        "",
        "Generated by `python reports/build_baseline_table.py`.",
        "",
        "## Split",
        "",
        f"- Primary split: temporal.",
        f"- Cutoff: train rows have `match_date < {cutoff.date()}`; "
        f"test rows have `match_date >= {cutoff.date()}`.",
        f"- Train rows: {len(train):,}.",
        f"- Test rows: {len(test):,}.",
        f"- Train conversion rate used by the global baseline: {train_rate:.1%}.",
        "",
        "## Metrics",
        "",
        _markdown_table(metrics),
        "",
        "Accuracy is included only as a footnote. The primary Step 6 metrics are "
        "log loss, Brier score, Brier Skill Score, AUCs, and ECE.",
        "",
        "## Notes",
        "",
        "- `shooter_raw` and `keeper_raw` fall back to the train global rate when "
        "a test row has no prior history for that player/keeper.",
        "- `shooter_shrunk` and `keeper_shrunk` use Step 5 as-of features, so they "
        "are the honest baselines later models must beat.",
        "- Keeper-dive baselines are not included because `keeper_dive_direction` "
        "has 0% coverage in the current StatsBomb-only dataset.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(), encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
